export enum QueryKeysEnum {
  Dashboard = "dashboard",
  Checklist = "checklists",
  ChecklistItem = "checklist-items",
  ChecklistCategory = "checklist-category",
  ChecklistTemplate = "checklist-template",
  ChecklistTemplateItem = "checklist-template-item",
  Carrier = "carriers",
  Event = "events",
  Part = "parts",
  Part_Request = "part-requests",
  Box = "boxes",
  Service = "services",
  Service_Assigment = "service-assignments",
  Trailer = "trailers",
  Work_Order = "work-orders",
  Fleet = "fleets",
  Employee = "employees",
  Vehicle = "vehicles",
  Note = "notes",
  Auth = "auth"
}