export enum PublicRoutes {
  Login = "/login",
  Register = "/auth/cadastrar",
  ForgotPassword = "/password/forgot",
}

export enum PrivateRoutes {
  Home = "/",
  CompanySelection = "/selecao-empresa",
  Carrier = "/cadastros/transportadoras",
  Fleet = "/cadastros/frota",
  Maintenance = "/cadastros/manutencao",
  Employees = "/cadastros/colaboradores",
  Services = "/cadastros/servicos",
  Trailer = "/cadastros/reboques",
  WorkShop = "/oficina",
  WorkOrders = "/ordem-de-servico",
  Settings = "/configuracoes",
  Account = "/configuracoes/minha-conta",
  Appearance = "/configuracoes/aparencia",
  Subscription = "/configuracoes/assinatura",
  Support = "/configuracoes/suporte",
  MaintenancePlanner = "/planejamento/manutencao",
  PartsManagement = "/planejamento/pecas",
  MaintenanceReports = "/relatorios/manutencao",
  CarrierReports = "/relatorios/transportadoras",
  FleetReports = "/relatorios/frota",
  ServicesReports = "/relatorios/servicos",
  EmployeesReports = "/relatorios/colaboradores",
}
