export enum PublicRoutes {
  Login = "/login",
  Register = "/auth/cadastrar",
  ForgotPassword = "/password/forgot",
}

export enum PrivateRoutes {
  Home = "/",
  CompanySelection = "/selecao-empresa",
  Carrier = "/gestao/transportadoras",
  Fleet = "/gestao/frota",
  Maintenance = "/gestao/manutencao",
  Employees = "/gestao/colaboradores",
  Services = "/gestao/servicos",
  Trailer = "/gestao/reboques",
  Vehicle = "/gestao/veiculos",
  Box = "/gestao/boxes",
  WorkShop = "/oficina",
  WorkOrders = "/ordem-de-servico",
  Settings = "/configuracoes",
  Account = "/configuracoes/minha-conta",
  Appearance = "/configuracoes/aparencia",
  Subscription = "/configuracoes/assinatura",
  Support = "/configuracoes/suporte",
  MaintenancePlanner = "/planejamento/manutencao",
  PartsManagement = "/planejamento/pecas",
  MaintenanceReports = "/relatorios/manutencao",
  CarrierReports = "/relatorios/transportadoras",
  FleetReports = "/relatorios/frota",
  ServicesReports = "/relatorios/servicos",
  EmployeesReports = "/relatorios/colaboradores",
  MaintenanceChecklist = "/manutencao/checklist",
}
